# 技術計算パッケージ scipy を使ってみよう

scipy https://www.scipy.org/ は科学技術用の計算パッケージです．
numpy をベースにして，様々な科学技術計算をサポートしています．
以下の行列をQR分解して下さい。

QR分解は，行列$A$ を分解するための手法で，直交行列($Q$)と上三角行列($R$)に分解します．
すなわち $A = QR$ の形に分解します．

実際にどこで使われているかというと最小二乗法の安定した数値解法などに用いられます．
→ 参考URL https://ja.wikipedia.org/wiki/%E6%9C%80%E5%B0%8F%E4%BA%8C%E4%B9%97%E6%B3%95

行列 $A$ を以下のように定義して，QR 分解を行ってみてください．
\begin{pmatrix}
2 & -2 & -1 \\
1 & -1 & 2 \\
-4 & -1 & 2 \\
2 & 3 & -1 \\ 
\end{pmatrix}

In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[2,-2,-1], [1,-1,2], [-4,-1,2], [2,3,-1]])  # □にPythonのリストを入れ指定の行列を作ってください。
print(A)

[[ 2 -2 -1]
 [ 1 -1  2]
 [-4 -1  2]
 [ 2  3 -1]]


In [9]:
Q, R = linalg.qr(A)  # □に入る linalg の関数を入れてください

In [10]:
print(Q)

[[-4.00000000e-01 -6.41426981e-01 -3.08606700e-01  5.77350269e-01]
 [-2.00000000e-01 -3.20713490e-01  9.25820100e-01  6.93889390e-17]
 [ 8.00000000e-01 -5.34522484e-02  1.54303350e-01  5.77350269e-01]
 [-4.00000000e-01  6.94879229e-01  1.54303350e-01  5.77350269e-01]]


In [11]:
print(R)

[[-5.         -1.          2.        ]
 [ 0.          3.74165739 -0.80178373]
 [ 0.          0.          2.31455025]
 [ 0.          0.          0.        ]]


求めた、Q及びRの行数及び列数を確認して下しい。

In [12]:
print(Q.shape)
assert Q.shape == (4, 4)
print(R.shape)
assert R.shape == (4, 3)

(4, 4)
(4, 3)


求めた、Q及びRが、A = QR が正しいことを確認して下しい。

In [13]:
np.allclose(A, Q @ R)

True

In [14]:
assert np.allclose(A, Q @ R)